# Generated by Django 2.2.6 on 2020-09-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='troubleshootinglogicblock',
            name='title',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
